# Generated by Django 4.1.1 on 2022-10-05 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_course_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category", options={"verbose_name_plural": "Categories"},
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=200, null=True)),
                ("answer", models.CharField(max_length=200, null=True)),
                ("option1", models.CharField(max_length=200, null=True)),
                ("option2", models.CharField(max_length=200, null=True)),
                ("option3", models.CharField(max_length=200, null=True)),
                ("option4", models.CharField(max_length=200, null=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="course.lesson",
                    ),
                ),
            ],
        ),
    ]
